# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pgranhol/mgc20-geant4/T1-gean4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pgranhol/mgc20-geant4/T1-gean4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pgranhol/mgc20-geant4/T1-gean4/CMakeFiles /home/pgranhol/mgc20-geant4/T1-gean4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pgranhol/mgc20-geant4/T1-gean4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named T1

# Build rule for target.
T1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T1
.PHONY : T1

# fast build rule for target.
T1/fast:
	$(MAKE) -f CMakeFiles/T1.dir/build.make CMakeFiles/T1.dir/build
.PHONY : T1/fast

#=============================================================================
# Target rules for targets named geantT1

# Build rule for target.
geantT1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 geantT1
.PHONY : geantT1

# fast build rule for target.
geantT1/fast:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/build
.PHONY : geantT1/fast

T1main.o: T1main.cc.o

.PHONY : T1main.o

# target to build an object file
T1main.cc.o:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/T1main.cc.o
.PHONY : T1main.cc.o

T1main.i: T1main.cc.i

.PHONY : T1main.i

# target to preprocess a source file
T1main.cc.i:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/T1main.cc.i
.PHONY : T1main.cc.i

T1main.s: T1main.cc.s

.PHONY : T1main.s

# target to generate assembly for a file
T1main.cc.s:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/T1main.cc.s
.PHONY : T1main.cc.s

src/T1ActionInitialization.o: src/T1ActionInitialization.cc.o

.PHONY : src/T1ActionInitialization.o

# target to build an object file
src/T1ActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1ActionInitialization.cc.o
.PHONY : src/T1ActionInitialization.cc.o

src/T1ActionInitialization.i: src/T1ActionInitialization.cc.i

.PHONY : src/T1ActionInitialization.i

# target to preprocess a source file
src/T1ActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1ActionInitialization.cc.i
.PHONY : src/T1ActionInitialization.cc.i

src/T1ActionInitialization.s: src/T1ActionInitialization.cc.s

.PHONY : src/T1ActionInitialization.s

# target to generate assembly for a file
src/T1ActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1ActionInitialization.cc.s
.PHONY : src/T1ActionInitialization.cc.s

src/T1DetectorConstruction.o: src/T1DetectorConstruction.cc.o

.PHONY : src/T1DetectorConstruction.o

# target to build an object file
src/T1DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1DetectorConstruction.cc.o
.PHONY : src/T1DetectorConstruction.cc.o

src/T1DetectorConstruction.i: src/T1DetectorConstruction.cc.i

.PHONY : src/T1DetectorConstruction.i

# target to preprocess a source file
src/T1DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1DetectorConstruction.cc.i
.PHONY : src/T1DetectorConstruction.cc.i

src/T1DetectorConstruction.s: src/T1DetectorConstruction.cc.s

.PHONY : src/T1DetectorConstruction.s

# target to generate assembly for a file
src/T1DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1DetectorConstruction.cc.s
.PHONY : src/T1DetectorConstruction.cc.s

src/T1PhysicsList.o: src/T1PhysicsList.cc.o

.PHONY : src/T1PhysicsList.o

# target to build an object file
src/T1PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1PhysicsList.cc.o
.PHONY : src/T1PhysicsList.cc.o

src/T1PhysicsList.i: src/T1PhysicsList.cc.i

.PHONY : src/T1PhysicsList.i

# target to preprocess a source file
src/T1PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1PhysicsList.cc.i
.PHONY : src/T1PhysicsList.cc.i

src/T1PhysicsList.s: src/T1PhysicsList.cc.s

.PHONY : src/T1PhysicsList.s

# target to generate assembly for a file
src/T1PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1PhysicsList.cc.s
.PHONY : src/T1PhysicsList.cc.s

src/T1PrimaryGeneratorAction.o: src/T1PrimaryGeneratorAction.cc.o

.PHONY : src/T1PrimaryGeneratorAction.o

# target to build an object file
src/T1PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1PrimaryGeneratorAction.cc.o
.PHONY : src/T1PrimaryGeneratorAction.cc.o

src/T1PrimaryGeneratorAction.i: src/T1PrimaryGeneratorAction.cc.i

.PHONY : src/T1PrimaryGeneratorAction.i

# target to preprocess a source file
src/T1PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1PrimaryGeneratorAction.cc.i
.PHONY : src/T1PrimaryGeneratorAction.cc.i

src/T1PrimaryGeneratorAction.s: src/T1PrimaryGeneratorAction.cc.s

.PHONY : src/T1PrimaryGeneratorAction.s

# target to generate assembly for a file
src/T1PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1PrimaryGeneratorAction.cc.s
.PHONY : src/T1PrimaryGeneratorAction.cc.s

src/T1RunAction.o: src/T1RunAction.cc.o

.PHONY : src/T1RunAction.o

# target to build an object file
src/T1RunAction.cc.o:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1RunAction.cc.o
.PHONY : src/T1RunAction.cc.o

src/T1RunAction.i: src/T1RunAction.cc.i

.PHONY : src/T1RunAction.i

# target to preprocess a source file
src/T1RunAction.cc.i:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1RunAction.cc.i
.PHONY : src/T1RunAction.cc.i

src/T1RunAction.s: src/T1RunAction.cc.s

.PHONY : src/T1RunAction.s

# target to generate assembly for a file
src/T1RunAction.cc.s:
	$(MAKE) -f CMakeFiles/geantT1.dir/build.make CMakeFiles/geantT1.dir/src/T1RunAction.cc.s
.PHONY : src/T1RunAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... T1"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... geantT1"
	@echo "... T1main.o"
	@echo "... T1main.i"
	@echo "... T1main.s"
	@echo "... src/T1ActionInitialization.o"
	@echo "... src/T1ActionInitialization.i"
	@echo "... src/T1ActionInitialization.s"
	@echo "... src/T1DetectorConstruction.o"
	@echo "... src/T1DetectorConstruction.i"
	@echo "... src/T1DetectorConstruction.s"
	@echo "... src/T1PhysicsList.o"
	@echo "... src/T1PhysicsList.i"
	@echo "... src/T1PhysicsList.s"
	@echo "... src/T1PrimaryGeneratorAction.o"
	@echo "... src/T1PrimaryGeneratorAction.i"
	@echo "... src/T1PrimaryGeneratorAction.s"
	@echo "... src/T1RunAction.o"
	@echo "... src/T1RunAction.i"
	@echo "... src/T1RunAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

